name: Self-hosted Intel OneAPI compilation and run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build_intel_champ_fparser:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: Compile and run
      run: |
        . /opt/intel/oneapi/setvars.sh
        ./compilefdf.sh
        echo "Build using Intel oneAPI compilers is successfull"

